[package]
name = "taskflow-api"
version = "0.1.0"
edition = "2024"

[dependencies]
# Framework Web
axum = { version = "0.8.8", features = ["macros"] }
tower-http = { version = "0.6.6", features = ["cors"] }
tokio = { version = "1", features = ["full"] }

# Base de datos
sqlx = { version = "0.8.6", features = [
    "runtime-tokio-rustls",
    "postgres",
    "chrono",
    "uuid",
    "migrate",
    "macros"
] }

# Cache Redis
redis = { version = "0.27", features = ["aio", "tokio-comp"] }

# Serialización
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Autenticación
jsonwebtoken = "10"
bcrypt = "0.15"

# Utilidades
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
once_cell = "1.19"
dotenvy = "0.15"

# Validación
validator = { version = "0.19", features = ["derive"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
